server:
  port: 9201
spring:
  application:
    name: spring-cloud-admin-center
  profiles:
    active: secure
  boot:
    admin:
      discovery:
        ignored-services: spring-cloud-admin-center
---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "123456"

